### ISSUE TITLE
"Error getting directions"

### ISSUE THREAD

**Issue by dingwilson** [chriswebb09/ARKitNavigationDemo#3]
When tapping a street on MKMapView, debug window shows:

>Error getting directions

When outputting the [error in Navigation.swift](https://github.com/chriswebb09/ARKitNavigationDemo/blob/master/ARKitNavigationDemo/ARKitNavigationDemo/Services/NavigationService.swift#L27), I get the following:

>Error Domain=MKLocationErrorDomain Code=5 "(null)"

**Comment by chriswebb09** [comment]
I think this has is stemming from the authorization issue as well. I'll keep you posted when I get to the fix.

**Comment by chriswebb09** [comment]
@dingwilson I think this should have it fixed, let me know if there is still an issue and I'll keep at it! Thanks for the feedback!

**Comment by dingwilson** [comment]
I think this issue has been fixed. Thanks!

**Comment by chriswebb09** [comment]
Awesome, great to hear!

**Comment by AbhinandanBedi** [comment]
@dingwilson @chriswebb09 Still getting the error "Error getting Directions". How did you guys manage to fix it?
